---
  - name: restart fail2ban
    service: name=fail2ban state=restarted
  - name: restart monit
    service: name=monit state=restarted
  - name: restart freeswitch
    service: name=freeswitch state=restarted
  - name: restart php-fpm
    service: name=php5-fpm state=restart
  - name: restart nginx
    service: name=nginx state=restarted
  - name: restart rsyslog
    service: name=rsyslog state=restarted
